### PR TITLE
Rename CV parts which got renamed

### PR DESCRIPTION
**Pull request by wrznr**
Trying to build PRLib failed due to changes in the OpenCV API.
This commit contains the necessary changes to enable building
PRLib with OpenCV Version 4.1.1.

### CODE REVIEW

**Comment by ZaMaZaN4iK** [comment]
Wow! I am wondered that someone uses my library!

**Comment by ZaMaZaN4iK** [comment]
@wrznr does it work with older OpenCV versions? Probably older OpenCV versions are still widely used.

**Comment by wrznr** [comment]
No. The API changes are “hard”. To allow for compatibility with older OpenCV versions, one would have to add lots of `DEFINE`s.

> someone uses my library

Not yet. Currently, I am in the process of getting everything built (including the samples!). But your library looks extremely promising. Just what we missed in the [OCR-D project](https://github.com/OCR-D).

**Comment by ZaMaZaN4iK** [comment]
Okay. I agree with you.

**Comment by wrznr** [comment]
Btw. there are preprocessing methods present in Tesseract (namely binarization and deskewing). They are not easily accessible but they are there. Thanks to the efforts of @bertsky, we have them available as separate processors within https://github.com/OCR-D/ocrd_tesserocr.

**Comment by ZaMaZaN4iK** [comment]
Yes, I know about them a lot. But honestly Tesseract preprocessing is VERY poor. And at my previous work we preprocessed an image a lot before recognizing with Tesseract.

**Comment by bertsky** [comment]
> But honestly Tesseract preprocessing is VERY poor.

I concur. Tesseract's binarization (global Otsu) does not even use Leptonica (as with dewarping), and deskewing is not even as good/reliable as the (entropy-based) method from ocropus-nlbin. But (compared to Ocropy) Tesseract recognition is surprisingly robust even without those.

> > someone uses my library
> 
> Not yet. Currently, I am in the process of getting everything built (including the samples!). But your library looks extremely promising. Just what we missed in the [OCR-D project](https://github.com/OCR-D).

I absolutely agree. OCR-D still lacks a good wrapper for OpenCV and Leptonica operations. 

@ZaMaZaN4iK Would it be difficult to add Python bindings in the same way [tesserocr does](https://github.com/sirfz/tesserocr/blob/417425d3dbe8043b9098b2257c105753257ae0e4/tesseract.pxd#L8), or even automatically like [opencv does](https://docs.opencv.org/4.1.1/da/d49/tutorial_py_bindings_basics.html)?

**Comment by ZaMaZaN4iK** [comment]
Currently I am not working on this library (because I am not working anymore in image processing area). So if you want Python bindings - I will be happy to take your contribution. Or you can fork this libary and do whatever you want :)

**Comment by bertsky** [comment]
> Currently I am not working on this library (because I am not working anymore in image processing area). So if you want Python bindings - I will be happy to take your contribution. Or you can fork this libary and do whatever you want :)

That's understood. I was merely asking your opinion on how this should/could be done.

**Pull request merged**
